# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "parallels/centos-7.3"
  config.vm.network "private_network", type: "dhcp"


  config.vm.define "server" do |server|
    server.vm.hostname = "server"
    config.vm.provision "ansible" do |ansible|
       ansible.playbook = "playbook.yml"
    end
  end

end